### PR TITLE
Feat: removed Sassquatch

### PR DESCRIPTION
**Pull request by yoo-brh**
- Removed Sassquatch package

### CODE REVIEW

**Comment by yoo-brh** [comment]
this is strange, I have same conflicts...

**Comment by yoo-brh** [comment]
> this is strange, I have same conflicts...

I think I had a local develop branch which seems does not exist anymore that I took as a reference... So I've created a new one from master. I've created a new one, but maybe no necessary?

**Review by RadLikeWhoa — APPROVED** [review]

**Comment by kelvinlouis** [comment]
just to be safe, can you re run npm i, so the package-lock removes deps from sassquatch that may no longer be used.

**Review by kelvinlouis — COMMENTED** [review]
see earlier comment in thread

**Comment by yoo-brh** [comment]
> just to be safe, can you re run npm i, so the package-lock removes deps from sassquatch that may no longer be used.

done

**Pull request merged**
